function fig = pcdCrossSectionTopography(fig, pFile,qFile,texts,X,Y)

P = pcd2mesh(pFile); 
Q = pcd2mesh(qFile);

[CX1,CY1,CP] = improfile(P(:,:,3),X,Y);
[CX1,CY1,CQ] = improfile(Q(:,:,3),X,Y);

xPoints=cumsum(sqrt(power(diff(CX1),2)+power(diff(CY1),2)));

figure(fig)

hVals1   = line(xPoints,1000*(CP(2:end)-CQ(2:end)));

set(hVals1,'Color','k','LineWidth', 1,'LineStyle','-');
       

hTitle  = title (texts.Title);
hXLabel = xlabel(texts.XLabel);
hYLabel = ylabel(texts.YLabel);
  
% hLegend = legend([hVals1], ...
%              texts.Legend{1});

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');

set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 2         );

xlim([1 length(xPoints)])