function fig = pcdMakeCrossSectionEPS(xPoints, C1, C2,C3, err,texts)


fig = figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;


hVals1   = line(xPoints,C1);
hVals2   = line(xPoints,C2);
hVals3   = line(xPoints,C3);
filledC = [C1',fliplr(C2')];

fillXPoints=[xPoints,fliplr(xPoints)];

hEBar    = errorbar(xPoints, C3, err);
hFill    = fill(fillXPoints,filledC,'k');%plot the data

set(hVals1,'Color','k','LineWidth', 1,'LineStyle','--');
set(hVals2,'Color','k','LineWidth', 1,'LineStyle','-.');
set(hVals3,'Color','k','LineWidth', 1.5,'LineStyle','-');
set(hEBar,'LineStyle', 'none','Marker', '.','Color', [.3 .3 .3]);
set(hFill,'FaceAlpha',0.2,'EdgeAlpha',0.2);%set edge color

set(hEBar,  'LineWidth',1, ...
            'Marker','o',...
            'MarkerSize', 6,...
            'MarkerEdgeColor', [.2 .2 .2],...
            'MarkerFaceColor' , [.7 .7 .7]);

        
hTitle  = title (texts.Title);
hXLabel = xlabel(texts.XLabel);
hYLabel = ylabel(texts.YLabel);
 
hLegend = legend([hVals1, hVals2, hVals3, hEBar], ...
             texts.Legend{1} , ...
             texts.Legend{2} , ...
             texts.Legend{3} , ...
             texts.Legend{4});

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 10           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 2         );

