function fig = pcdVelocityCSEPS(fig,xPoints,Velocity,texts)


% fig = figure('Units', 'pixels', ...
%     'Position', [100 100 700 375]);
hold on;

figure(fig)

hVals1   = line(xPoints,Velocity);

set(hVals1,'Color','k','LineWidth', 1,'LineStyle','-');
       
hTitle  = title (texts.Title);
hXLabel = xlabel(texts.XLabel);
hYLabel = ylabel(texts.YLabel);
%  
hLegend = legend([hVals1], ...
             texts.Legend{1});

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Helvetica');
% set([hLegend, gca]             , ...
%     'FontSize'   , 10           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          );
set( hTitle                    , ...
    'FontSize'   , 14          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'off'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 2         );

